"""Standalone PPA sourcing cost sweep.

This script reuses the existing ENTSOE CSV loading helpers from
RFNBO_orchestrator.py and the PPA production helper in rfnbo_calculations.py.

It sweeps PPA-to-electrolyser ratios and day-ahead market (DAM) premiums to estimate
the sourcing cost of a PPA referenced to the DAM. 

### Cost Calculation Logic (Financial PPA Settlement)
The script models the PPA purely financially. All electrolyser consumption is assumed 
to be purchased from the day-ahead market, and the PPA premium is settled separately:

    Baseline Grid Cost = Total Electrolyser Consumption * DAM price
    Incremental PPA Cost = Matched PPA Energy * Margin
    Total Cost = Baseline Grid Cost + Incremental PPA Cost

Note on "Residual Grid Energy": 
While the script calculates a `grid_energy_mwh` (residual grid) metric, this is strictly 
used for volume reporting in the summary CSV (to show how much physical energy was not 
matched by the PPA). It is NOT used in the cost calculations, because the baseline 
DAM price is already applied to 100% of the electrolyser's consumption.

### Expected Inputs
* **Market Data:** ENTSO-E generation, prices, and installed capacity CSVs (loaded from the specified `--data-dir`).
* **Electrolyser Capacity:** Required baseline load defined via `--electrolyser-mw`.
* **RFNBO Sweep Data:** A pre-calculated CSV mapping PPA ratios to RFNBO compliance fractions (generated by `rfnbo_ratio_sweep_cli.py` or calculated on-the-fly).

### Expected Outputs
1.  **Detailed CSV (`*_ppa_sourcing_cost_detail.csv`):** Row-by-row temporal calculations of energy and cost for every timestep and scenario.
2.  **Summary CSV (`*_ppa_sourcing_cost_summary.csv`):** Compact aggregations showing total energy volumes, average costs (€/MWh), PPA shares, and overall RFNBO compliance per swept scenario.
3.  **Interactive Plot (`*_ppa_sourcing_cost_summary_plot.html`):** An HTML scatter plot showing the aggregated cost against the PPA-to-electrolyser ratio, categorized by technology type and margin.

### Example CLI Usage

**1. Basic Run (Defaults for Belgium):**
Runs the sweep using default ratios (0.0 to 2.0) and margins (1 to 5 EUR/MWh) for a 100 MW electrolyser, automatically opening the HTML plot when finished.
> python ppa_sweep.py --country Belgium --electrolyser-mw 100 --open-html

**2. Targeted Scenario Sweep:**
Evaluates specific PPA-to-electrolyser ratios and margins for only Solar and Wind Onshore, using hourly temporal correlation.
> python ppa_sweep.py \
    --country Germany \
    --electrolyser-mw 50 \
    --ratios 0.5 1.0 1.5 \
    --margins 2.0 4.0 \
    --technologies "Solar" "Wind Onshore" \
    --temporal-correlation hourly

**3. Specific Date Range and File Paths:**
Runs the sweep for a specific year, explicitly passing the required pre-computed RFNBO sweep CSV instead of searching the default outputs directory.
> python ppa_sweep.py \
    --country France \
    --electrolyser-mw 200 \
    --start 2023-01-01 --end 2023-12-31 \
    --rfnbo-file custom_folder/France_hourly_ratio_sweep.csv
"""

from __future__ import annotations

import argparse
import webbrowser
from pathlib import Path

import pandas as pd
import plotly.express as px
import numpy as np
import logging

logger = logging.getLogger(__name__)

from RFNBO_orchestrator import (
    _filter_date_range,
    _find_latest_file,
    _load_generation,
    _load_installed_capacity,
    _load_prices,
)
from rfnbo_calculations import (
    calculate_renewable_share,
    calculate_ppa_production_from_generation_data,
    integrate_power_to_energy,
    calculate_rfnbo_compliance,
)


DEFAULT_RATIOS = [round(index * 0.25, 2) for index in range(0, 9)]
DEFAULT_MARGINS = [1.0, 2.0, 3.0, 4.0, 5.0]
DEFAULT_TECHNOLOGIES = [
    "Solar",
    "Wind Offshore",
    "Wind Onshore",
    "Solar + Wind Offshore",
    "Solar + Wind Onshore",
]

TECHNOLOGY_LABELS = {
    "Solar": "Solar",
    "Wind Onshore": "Wind Onshore",
    "Wind Offshore": "Wind Offshore",
    "Solar + Wind Offshore": "Solar + Wind Offshore",
    "Solar + Wind Onshore": "Solar + Wind Onshore",
}


def _tech_slug(technology: str) -> str:
    return technology.lower().replace(" + ", "_plus_").replace(" ", "_")


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Estimate PPA sourcing cost using a day-ahead market reference price "
            "plus an adjustable premium, swept across PPA-to-load ratios."
        )
    )
    parser.add_argument("--country", default="Belgium", help="Country folder name under entsoe_data")
    parser.add_argument("--data-dir", default="entsoe_data", help="Base directory containing country subfolders")
    parser.add_argument(
        "--temporal-correlation",
        choices=["hourly", "monthly"],
        default="hourly",
        help="Aggregation mode for the sweep output",
    )
    parser.add_argument(
        "--ratios",
        nargs="+",
        type=float,
        default=DEFAULT_RATIOS,
        help="Production-to-consumption ratios to sweep (default: 0.0 to 2.0 in 0.25 steps)",
    )
    parser.add_argument(
        "--margins",
        nargs="+",
        type=float,
        default=DEFAULT_MARGINS,
        help="Extra DAM premiums in EUR/MWh to sweep (default: 1 to 5 EUR/MWh)",
    )
    parser.add_argument(
        "--technologies",
        nargs="+",
        default=DEFAULT_TECHNOLOGIES,
        choices=list(TECHNOLOGY_LABELS),
        help="PPA technologies to model (default: Solar, wind, and 50/50 combined cases)",
    )
    parser.add_argument(
        "--solar-fraction",
        type=float,
        help="Optional solar share for combined PPA technologies (solar fraction of combined PPA)",
    )
    parser.add_argument("--prices-file", help="Optional explicit path to prices CSV")
    parser.add_argument("--generation-file", help="Optional explicit path to generation CSV")
    parser.add_argument("--capacity-file", help="Optional explicit path to installed capacity CSV")
    parser.add_argument(
        "--rfnbo-file",
        help="Optional explicit path to the ratio sweep CSV. Defaults to outputs/<country>_<mode>_ratio_sweep.csv",
    )
    parser.add_argument(
        "--ppa-series-file",
        help="Optional path to a precomputed temporal PPA series CSV (timestamp + per-tech columns). If provided, used instead of computing PPA production.",
    )
    parser.add_argument(
        "--rfnbo-recalc-missing",
        action="store_true",
        help="Recalculate RFNBO on-the-fly when the requested ratio is missing from the RFNBO sweep CSV (slower).",
    )
    parser.add_argument("--start", help="Optional start date filter (YYYY-MM-DD)")
    parser.add_argument("--end", help="Optional end date filter (YYYY-MM-DD)")
    parser.add_argument("--electrolyser-mw", type=float, required=True, help="Electrolyser capacity in MW")
    parser.add_argument(
        "--output-dir",
        default="outputs",
        help="Directory to store CSV and HTML outputs",
    )
    parser.add_argument(
        "--output-file",
        help="Optional detailed CSV path. Defaults to outputs/<country>_<mode>_ppa_sourcing_cost_detail.csv",
    )
    parser.add_argument(
        "--summary-file",
        help="Optional summary CSV path. Defaults to outputs/<country>_<mode>_ppa_sourcing_cost_summary.csv",
    )
    parser.add_argument(
        "--plot-file",
        help="Optional HTML plot path. Defaults to outputs/<country>_<mode>_ppa_sourcing_cost.html",
    )
    parser.add_argument(
        "--open-html",
        action="store_true",
        help="Open the generated HTML plot in the default browser",
    )
    return parser


def _load_input_data(args: argparse.Namespace) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    country_dir = Path(args.data_dir) / args.country
    if not country_dir.exists():
        raise FileNotFoundError(f"Country folder not found: {country_dir}")

    prices_file = (
        Path(args.prices_file)
        if args.prices_file
        else _find_latest_file(country_dir, f"{args.country}_prices_*.csv")
    )
    generation_file = (
        Path(args.generation_file)
        if args.generation_file
        else _find_latest_file(country_dir, f"{args.country}_generation_*.csv")
    )
    capacity_file = (
        Path(args.capacity_file)
        if args.capacity_file
        else _find_latest_file(country_dir, f"{args.country}_installed_capacity_*.csv")
    )

    prices_df = _load_prices(prices_file)
    generation_df = _load_generation(generation_file)
    capacity_df = _load_installed_capacity(capacity_file)

    prices_df, generation_df = _filter_date_range(prices_df, generation_df, args.start, args.end)

    if prices_df.empty:
        raise ValueError("No prices data left after applying date filters.")
    if generation_df.empty:
        raise ValueError("No generation data left after applying date filters.")

    return prices_df, generation_df, capacity_df


def _load_rfnbo_sweep_data(args: argparse.Namespace) -> pd.DataFrame:
    rfnbo_file = Path(args.rfnbo_file) if args.rfnbo_file else Path(args.output_dir) / f"{args.country}_{args.temporal_correlation}_ratio_sweep.csv"
    if not rfnbo_file.exists():
        raise FileNotFoundError(
            f"RFNBO ratio sweep CSV not found: {rfnbo_file}. Run rfnbo_ratio_sweep_cli.py first or pass --rfnbo-file."
        )

    rfnbo_df = pd.read_csv(rfnbo_file)
    required = {
        "country",
        "technology",
        "ppa_to_electrolyser_ratio",
        "temporal_correlation",
        "interval_label",
        "overall_rfnbo_fraction",
        "overall_rfnbo_pct",
    }
    missing = required.difference(rfnbo_df.columns)
    if missing:
        raise ValueError(f"RFNBO sweep CSV is missing required columns: {sorted(missing)}")

    # normalize technology names to help robust matching
    def _norm(s: str) -> str:
        return "".join(ch for ch in str(s).lower() if ch.isalnum())

    rfnbo_df["tech_norm"] = rfnbo_df["technology"].apply(_norm)
    # ensure ratio numerical type
    rfnbo_df["ppa_to_electrolyser_ratio"] = rfnbo_df["ppa_to_electrolyser_ratio"].astype(float)
    # trim interval labels
    rfnbo_df["interval_label"] = rfnbo_df["interval_label"].astype(str)

    return rfnbo_df


def _load_ppa_series(args: argparse.Namespace) -> pd.DataFrame | None:
    if not args.ppa_series_file:
        return None
    p = Path(args.ppa_series_file)
    if not p.exists():
        raise FileNotFoundError(f"PPA series CSV not found: {p}")
    df = pd.read_csv(p, parse_dates=["timestamp"], low_memory=False)
    # normalize timestamp column name to `datetime` to match prices_df
    if "datetime" not in df.columns:
        if "timestamp" in df.columns:
            df = df.rename(columns={"timestamp": "datetime"})
        else:
            raise ValueError("PPA series CSV must contain a 'timestamp' or 'datetime' column")
    # If the file only contains timestamps (no per-technology columns), ignore it
    if set(df.columns) == {"datetime"}:
        logger.warning("PPA series file contains no per-technology columns; ignoring and computing PPA production instead")
        return None
    return df
def _scenario_rows(
    prices_df: pd.DataFrame,
    generation_df: pd.DataFrame,
    capacity_df: pd.DataFrame,
    rfnbo_sweep_df: pd.DataFrame,
    country: str,
    electrolyser_mw: float,
    ratio: float,
    technology: str,
    mode: str,
    solar_fraction: float | None,
    recalc_missing_rfnbo: bool = False,
    ppa_series_df: pd.DataFrame | None = None,
) -> pd.DataFrame:
    ppa_capacity_mw = electrolyser_mw * ratio
    if ppa_capacity_mw < 0:
        return pd.DataFrame()

    # Optionally use precomputed PPA series (timestamp + per-tech columns)
    if ppa_series_df is not None:
        # map technology to series columns (solar/offshore/onshore)
        tech_keys = []
        t = technology.lower()
        if "solar" in t:
            tech_keys.append("solar")
        if "offshore" in t:
            tech_keys.append("offshore")
        if "onshore" in t:
            tech_keys.append("onshore")

        available_cols = [c for c in ppa_series_df.columns if c != "datetime"]
        selected_cols = [c for c in available_cols if any(k in c.lower() for k in tech_keys)]
        if selected_cols:
            tmp = ppa_series_df[["datetime"] + selected_cols].copy()
            # sum across tech columns to a single ppa production column
            tmp["ppa_production_mw"] = tmp[selected_cols].sum(axis=1)
            ppa_production_df = tmp[["datetime", "ppa_production_mw"]].copy()
        else:
            # No matching columns found; fall back to calculated production
            ppa_production_df = calculate_ppa_production_from_generation_data(
                generation_df=generation_df,
                ppa_technology=technology,
                ppa_capacity_mw=ppa_capacity_mw,
                prices_df=prices_df,
                installed_capacity_df=capacity_df,
                solar_fraction=solar_fraction,
                wind_fraction=(1.0 - solar_fraction) if solar_fraction is not None else None,
            )
    else:
        ppa_production_df = calculate_ppa_production_from_generation_data(
            generation_df=generation_df,
            ppa_technology=technology,
            ppa_capacity_mw=ppa_capacity_mw,
            prices_df=prices_df,
            installed_capacity_df=capacity_df,
            solar_fraction=solar_fraction,
            wind_fraction=(1.0 - solar_fraction) if solar_fraction is not None else None,
        )

    if ppa_production_df.empty:
        return pd.DataFrame()

    df = prices_df.copy()
    if "resolution_minutes" not in df.columns:
        df["resolution_minutes"] = 60
    df["electrolyser_consumption_mw"] = electrolyser_mw
    df = integrate_power_to_energy(
        df,
        power_column="electrolyser_consumption_mw",
        energy_column="electrolyser_consumption_mwh",
        resolution_column="resolution_minutes",
        timestamp_column="datetime",
    )

    df = df.merge(ppa_production_df, on="datetime", how="left")
    df["ppa_production_mw"] = df["ppa_production_mw"].fillna(0)
    df = integrate_power_to_energy(
        df,
        power_column="ppa_production_mw",
        energy_column="ppa_energy_mwh_raw",
        resolution_column="resolution_minutes",
        timestamp_column="datetime",
    )

    if mode == "hourly":
        df["ppa_energy_mwh"] = df[["ppa_energy_mwh_raw", "electrolyser_consumption_mwh"]].min(axis=1)
    else:
        df["ppa_energy_mwh"] = df["ppa_energy_mwh_raw"]

    df["grid_energy_mwh"] = (df["electrolyser_consumption_mwh"] - df["ppa_energy_mwh"]).clip(lower=0)

    # robust matching: normalize technology and use isclose for ratio
    def _norm(s: str) -> str:
        return "".join(ch for ch in str(s).lower() if ch.isalnum())

    tech_norm = _norm(technology)
    mask = (
        (rfnbo_sweep_df["country"] == country)
        & (rfnbo_sweep_df["temporal_correlation"] == mode)
        & rfnbo_sweep_df["tech_norm"].eq(tech_norm)
        & np.isclose(rfnbo_sweep_df["ppa_to_electrolyser_ratio"].astype(float), float(ratio), atol=1e-6)
    )

    sweep_match = rfnbo_sweep_df.loc[mask, ["interval_label", "overall_rfnbo_fraction", "overall_rfnbo_pct"]].copy()

    matched_ratio = None
    if sweep_match.empty:
        # try to find the nearest available ratio for this country/tech/mode
        candidates = rfnbo_sweep_df[
            (rfnbo_sweep_df["country"] == country)
            & (rfnbo_sweep_df["temporal_correlation"] == mode)
            & rfnbo_sweep_df["tech_norm"].eq(tech_norm)
        ].copy()

        if not candidates.empty:
            candidates["_ratio_f"] = candidates["ppa_to_electrolyser_ratio"].astype(float)
            # pick nearest ratio available
            nearest_idx = (candidates["_ratio_f"] - float(ratio)).abs().idxmin()
            matched_ratio = candidates.loc[nearest_idx, "ppa_to_electrolyser_ratio"]
            sweep_match = candidates[candidates["ppa_to_electrolyser_ratio"] == matched_ratio][["interval_label", "overall_rfnbo_fraction", "overall_rfnbo_pct"]].copy()

    if sweep_match.empty:
        # no RFNBO data at all for this tech+mode
        if recalc_missing_rfnbo:
            # Recalculate RFNBO for this scenario (slower) using existing calc function
            recalc_df = calculate_rfnbo_compliance(
                electrolyser_mw=electrolyser_mw,
                ppa_capacity_mw=ppa_capacity_mw,
                prices_df=prices_df,
                renewable_share=calculate_renewable_share(generation_df),
                zone_name=country,
                temporal_correlation=mode,
                use_price_threshold=True,
                ppa_technology=technology,
                generation_df=generation_df,
                installed_capacity_df=capacity_df,
                solar_fraction=solar_fraction,
                wind_fraction=(1.0 - solar_fraction) if solar_fraction is not None else None,
            )

            if recalc_df.empty:
                df["country"] = country
                df["technology"] = technology
                df["ppa_to_electrolyser_ratio"] = ratio
                df["ppa_capacity_mw"] = ppa_capacity_mw
                df["electrolyser_mw"] = electrolyser_mw
                df["temporal_correlation"] = mode
                df["overall_rfnbo_fraction"] = pd.NA
                df["overall_rfnbo_pct"] = pd.NA
                df["rfnbo_energy_mwh"] = pd.NA
                df["rfnbo_matched_ratio"] = pd.NA
                df["rfnbo_recalc_used"] = False
                return df

            # create sweep_match from recalculated df
            if mode == "monthly":
                recalc_df["interval_label"] = pd.to_datetime(recalc_df["datetime"]).dt.strftime("%Y-%m")
            else:
                recalc_df["interval_label"] = pd.to_datetime(recalc_df["datetime"]).dt.strftime("%Y-%m-%d %H:%M")

            sweep_match = recalc_df[["interval_label", "rfnbo_fraction"]].rename(columns={"rfnbo_fraction": "overall_rfnbo_fraction"}).copy()
            sweep_match["overall_rfnbo_pct"] = sweep_match["overall_rfnbo_fraction"] * 100
            matched_ratio = ratio
            # proceed to merge below, but mark that we used recalculation
            recalc_used = True
        else:
            df["country"] = country
            df["technology"] = technology
            df["ppa_to_electrolyser_ratio"] = ratio
            df["ppa_capacity_mw"] = ppa_capacity_mw
            df["electrolyser_mw"] = electrolyser_mw
            df["temporal_correlation"] = mode
            df["overall_rfnbo_fraction"] = pd.NA
            df["overall_rfnbo_pct"] = pd.NA
            df["rfnbo_energy_mwh"] = pd.NA
            df["rfnbo_matched_ratio"] = pd.NA
            df["rfnbo_recalc_used"] = False
            return df

    if mode == "monthly":
        df["period_label"] = pd.to_datetime(df["datetime"], utc=True).dt.strftime("%Y-%m")
    else:
        df["period_label"] = pd.to_datetime(df["datetime"], utc=True).dt.strftime("%Y-%m-%d %H:%M")

    df = df.merge(sweep_match, left_on="period_label", right_on="interval_label", how="left")
    if df.empty:
        return pd.DataFrame()

    # annotate which RFNBO ratio was actually used (nearest match)
    df["rfnbo_matched_ratio"] = matched_ratio if matched_ratio is not None else df.get("ppa_to_electrolyser_ratio")
    # whether we recalculated RFNBO for this scenario
    df["rfnbo_recalc_used"] = True if 'recalc_used' in locals() and recalc_used else False

    df["country"] = country
    df["technology"] = technology
    df["ppa_to_electrolyser_ratio"] = ratio
    df["ppa_capacity_mw"] = ppa_capacity_mw
    df["electrolyser_mw"] = electrolyser_mw
    df["temporal_correlation"] = mode
    df["overall_rfnbo_fraction"] = df["overall_rfnbo_fraction"].astype(float)
    df["overall_rfnbo_pct"] = df["overall_rfnbo_pct"].astype(float)
    df["rfnbo_energy_mwh"] = df["overall_rfnbo_fraction"] * df["electrolyser_consumption_mwh"]
    return df


def _apply_cost_columns(detail_df: pd.DataFrame, margin_eur_mwh: float) -> pd.DataFrame:
    df = detail_df.copy()
    df["extra_margin_eur_mwh"] = margin_eur_mwh
    df["ppa_price_eur_mwh"] = df["price_eur_mwh"] + margin_eur_mwh
    df["baseline_cost_eur"] = df["electrolyser_consumption_mwh"] * df["price_eur_mwh"]
    df["ppa_cost_eur"] = df["ppa_energy_mwh"] * margin_eur_mwh
    df["incremental_cost_eur"] = df["ppa_cost_eur"]
    df["total_cost_eur"] = df["baseline_cost_eur"] + df["incremental_cost_eur"]
    df["absolute_cost_eur_mwh"] = df["total_cost_eur"] / df["electrolyser_consumption_mwh"].where(
        df["electrolyser_consumption_mwh"] > 0,
        pd.NA,
    )
    df["incremental_cost_eur_mwh"] = df["incremental_cost_eur"] / df["electrolyser_consumption_mwh"].where(
        df["electrolyser_consumption_mwh"] > 0,
        pd.NA,
    )
    df["ppa_share_pct"] = (
        df["ppa_energy_mwh"] / df["electrolyser_consumption_mwh"].where(df["electrolyser_consumption_mwh"] > 0, pd.NA)
    ) * 100
    return df


def _summarise_scenario(detail_df: pd.DataFrame) -> pd.DataFrame:
    if detail_df.empty:
        return detail_df

    summary_rows: list[dict[str, float | str]] = []
    group_columns = [
        "country",
        "technology",
        "ppa_to_electrolyser_ratio",
        "extra_margin_eur_mwh",
        "ppa_capacity_mw",
        "electrolyser_mw",
        "temporal_correlation",
    ]

    for group_values, group_df in detail_df.groupby(group_columns, dropna=False):
        total_consumption_mwh = group_df["electrolyser_consumption_mwh"].sum()
        total_ppa_mwh = group_df["ppa_energy_mwh"].sum()
        total_grid_mwh = group_df["grid_energy_mwh"].sum()
        total_cost_eur = group_df["total_cost_eur"].sum()
        baseline_cost_eur = group_df["baseline_cost_eur"].sum()
        incremental_cost_eur = group_df["incremental_cost_eur"].sum()
        absolute_cost_eur_mwh = total_cost_eur / total_consumption_mwh if total_consumption_mwh > 0 else 0.0
        incremental_cost_eur_mwh = incremental_cost_eur / total_consumption_mwh if total_consumption_mwh > 0 else 0.0
        ppa_share_pct = (total_ppa_mwh / total_consumption_mwh * 100) if total_consumption_mwh > 0 else 0.0
        total_rfnbo_mwh = group_df["rfnbo_energy_mwh"].sum(min_count=1)
        overall_rfnbo_fraction = (total_rfnbo_mwh / total_consumption_mwh) if total_consumption_mwh > 0 and pd.notna(total_rfnbo_mwh) else pd.NA

        summary_rows.append(
            {
                "country": group_values[0],
                "technology": group_values[1],
                "ppa_to_electrolyser_ratio": group_values[2],
                "extra_margin_eur_mwh": group_values[3],
                "ppa_capacity_mw": group_values[4],
                "electrolyser_mw": group_values[5],
                "temporal_correlation": group_values[6],
                "total_consumption_mwh": total_consumption_mwh,
                "total_ppa_energy_mwh": total_ppa_mwh,
                "total_grid_energy_mwh": total_grid_mwh,
                "baseline_cost_eur": baseline_cost_eur,
                "incremental_cost_eur": incremental_cost_eur,
                "total_cost_eur": total_cost_eur,
                "absolute_cost_eur_mwh": absolute_cost_eur_mwh,
                "incremental_cost_eur_mwh": incremental_cost_eur_mwh,
                "ppa_share_pct": ppa_share_pct,
                "overall_rfnbo_fraction": overall_rfnbo_fraction,
                "overall_rfnbo_pct": overall_rfnbo_fraction * 100 if pd.notna(overall_rfnbo_fraction) else pd.NA,
            }
        )

    summary_df = pd.DataFrame(summary_rows)
    return summary_df.sort_values(["extra_margin_eur_mwh", "ppa_to_electrolyser_ratio"])


def _build_summary_plot(df: pd.DataFrame, country: str, mode: str, output_path: Path) -> None:
    if df.empty:
        return

    plot_df = df.copy()
    plot_df["rfnbo_marker_size"] = plot_df["overall_rfnbo_pct"].fillna(4.0).clip(lower=4.0)

    fig = px.scatter(
        plot_df,
        x="ppa_to_electrolyser_ratio",
        y="absolute_cost_eur_mwh",
        color="extra_margin_eur_mwh",
        symbol="technology",
        category_orders={"technology": list(TECHNOLOGY_LABELS)},
        symbol_sequence=["circle", "square", "diamond", "x", "cross"],
        size="rfnbo_marker_size",
        size_max=22,
        color_continuous_scale="Viridis",
        hover_data={
            "technology": True,
            "extra_margin_eur_mwh": ":.1f",
            "incremental_cost_eur": ":.2f",
            "total_cost_eur": ":.2f",
            "overall_rfnbo_pct": ":.1f",
            "ppa_share_pct": ":.1f",
            "baseline_cost_eur": ":.2f",
            "incremental_cost_eur_mwh": ":.2f",
            "absolute_cost_eur_mwh": ":.2f",
            "ppa_capacity_mw": ":.1f",
            "electrolyser_mw": ":.1f",
        },
        title=f"PPA aggregated cost vs production-to-consumption ratio - {country} ({mode})",
        labels={
            "ppa_to_electrolyser_ratio": "Production to consumption ratio",
            "absolute_cost_eur_mwh": "Aggregated cost [€/MWh]",
            "extra_margin_eur_mwh": "Extra margin [€/MWh]",
            "overall_rfnbo_pct": "RFNBO [%]",
        },
    )

    fig.update_traces(marker=dict(opacity=0.85, line=dict(width=0.5, color="rgba(0,0,0,0.35)")))
    fig.update_layout(
        template="plotly_white",
        margin=dict(l=70, r=170, t=70, b=100),
        legend=dict(
            title_text="Technology",
            x=1.02,
            y=0.98,
            bgcolor="rgba(255,255,255,0.85)",
            bordercolor="rgba(0,0,0,0.1)",
            borderwidth=1,
        ),
        coloraxis_colorbar=dict(
            title="Extra margin [€/MWh]",
            x=1.18,
            thickness=18,
        ),
    )
    fig.update_xaxes(tickmode="linear", dtick=0.25)
    fig.update_yaxes(ticksuffix=" €/MWh")
    fig.write_html(output_path)


def main() -> None:
    parser = _build_parser()
    args = parser.parse_args()

    if args.solar_fraction is not None and not (0.0 <= args.solar_fraction <= 1.0):
        raise ValueError("--solar-fraction must be between 0 and 1")

    prices_df, generation_df, capacity_df = _load_input_data(args)
    renewable_share = calculate_renewable_share(generation_df)
    rfnbo_sweep_df = _load_rfnbo_sweep_data(args)
    ppa_series_df = _load_ppa_series(args)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    detail_frames: list[pd.DataFrame] = []
    summary_frames: list[pd.DataFrame] = []
    for technology in args.technologies:
        solar_fraction = args.solar_fraction
        if solar_fraction is None and "+" in technology:
            solar_fraction = 0.5

        for ratio in args.ratios:
            base_detail_df = _scenario_rows(
                prices_df=prices_df,
                generation_df=generation_df,
                capacity_df=capacity_df,
                rfnbo_sweep_df=rfnbo_sweep_df,
                recalc_missing_rfnbo=args.rfnbo_recalc_missing,
                ppa_series_df=ppa_series_df,
                country=args.country,
                electrolyser_mw=args.electrolyser_mw,
                ratio=ratio,
                technology=technology,
                mode=args.temporal_correlation,
                solar_fraction=solar_fraction,
            )

            if base_detail_df.empty:
                continue

            for margin in args.margins:
                print(f"Running {technology} ratio {ratio:g} margin {margin:g} €/MWh...")
                detail_df = _apply_cost_columns(base_detail_df, margin)
                detail_frames.append(detail_df)
                summary_frames.append(_summarise_scenario(detail_df))

    if not detail_frames:
        raise ValueError("PPA sourcing cost sweep produced no rows.")

    detail_out = Path(args.output_file) if args.output_file else output_dir / f"{args.country}_{args.temporal_correlation}_ppa_sourcing_cost_detail.csv"
    summary_out = Path(args.summary_file) if args.summary_file else output_dir / f"{args.country}_{args.temporal_correlation}_ppa_sourcing_cost_summary.csv"
    plot_out = Path(args.plot_file) if args.plot_file else output_dir / f"{args.country}_{args.temporal_correlation}_ppa_sourcing_cost.html"

    detail_df = pd.concat(detail_frames, ignore_index=True)
    summary_df = pd.concat(summary_frames, ignore_index=True)
    detail_df.to_csv(detail_out, index=False)
    summary_df.to_csv(summary_out, index=False)

    plot_out = Path(args.plot_file) if args.plot_file else output_dir / f"{args.country}_{args.temporal_correlation}_ppa_sourcing_cost_summary_plot.html"
    _build_summary_plot(summary_df, args.country, args.temporal_correlation, plot_out)

    print(detail_out)
    print(summary_out)
    print(plot_out)

    if args.open_html:
        webbrowser.open(plot_out.resolve().as_uri())


if __name__ == "__main__":
    main()